DM-21706: Add filter definitions to support BOT
lsst/obs_lsst pull request #251
Opened 2020-09-14 22:21 UTC by RobertLuptonTheGood

Now with LATISS!  #250 was just to discuss with Tim

2020-09-15 22:09 UTC, mfisherlevine requested changes
Some changes, and a rebase needed.

2020-09-15 22:09 UTC, mfisherlevine commented on python/lsst/obs/lsst/filters.py
> +            af = f"{abstract_filter}~{nd.replace('.', '_')}"
I think I get what this block is doing, but boy did I have to stare at it for a minute. I wonder if it could be clearer... At least I think it deserves a comment on what it's trying to achieve.

2020-09-15 22:34 UTC, timj commented on python/lsst/obs/lsst/lsstCamMapper.py
> +            except pexExceptions.NotFoundError:
Please catch a `LookupError` here rather than trying to specifically catch pexExceptions. We are generally trying to avoid pex.exceptions in python unless it's critical that we be able to catch that variant.

2020-09-15 22:37 UTC, timj commented on python/lsst/obs/lsst/lsstCamMapper.py
> +            obsInfo = ObservationInfo(exp.getMetadata())
You can give this a hint by adding `translator_class=self.translatorClass` as a second argument.

2020-09-15 22:39 UTC, timj commented on tests/test_comCam.py
> +        filters = {'raw': 'UNKNOWN',
Can you give us a clue?

2020-09-16 00:15 UTC, mfisherlevine commented on tests/test_comCam.py
> +        filters = {'raw': 'UNKNOWN',
The OOB chat was about what these _mean_. NONE should be used for "there was no filter in place" _i.e._ equivalent to EMPTY (NB this is different from BLANK or CLEAR which means clear glass, but of a non-blocking kind) whereas UNKNOWN means we don't have sufficient information to say what this is, so either there was no header key present, or it was present but it was an empty card, or it contained a string that we were unable to map, so the filter remains a mystery and could be anything in reality.

2020-09-16 00:16 UTC, mfisherlevine commented on tests/test_comCam.py
> +        filters = {'raw': 'UNKNOWN',
The objection to these changes was therefore that, given the above, this was a semantic difference, as NONE and UNKNOWN are not equivalent. However, it turns out that this is actually correct, and was previously wrong, as there was no information present in the test file, I am told.

2020-09-16 00:34 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/lsstCamMapper.py
> +                            obsInfo.observation_id, obsInfo.detector_unique_name,
I want the user to be able to find the offending file unambiguously.  I agree that it won't matter modulo CCS bugs/data corruption

2020-09-16 00:36 UTC, RobertLuptonTheGood commented on tests/test_lsstCam.py
> +        filters = {'raw': 'UNKNOWN',
Summary: there is no `FILTER` keyword, so `UNKNOWN` is more appropriate than NONE.  I suppose I could rebase the file to add this fact to the commit comment, but is it worth it?

2020-09-16 00:37 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +_latiss_gratings = ("ronchi90lpmm", "ronchi170lpmm", "EMPTY", "NONE", "UNKNOWN")
We agreed that this is a better name, and I'll add a commit making this change.

2020-09-16 00:39 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +                            ("z", "SN-02 "),
I checked this with Brian when it first came up.  No, there are two different thicknesses of glass, and the SN is unique within the glass thickness.   Fortunately, the `physical_filter` includes both coating (e.g. `u`) and serial number so this isn't visible to the Rubin system.

2020-09-16 00:40 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +                            ("i", "SN-06"),
Yes;  see above

2020-09-16 00:42 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +]
Yes;  but if we add e.g. a blank filter it'll be a second line in the initialisation list.  I think I'll leave it this way.

2020-09-16 00:43 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +    if abstract_filter == "clear":
Cut-and-paste.  "clear" isn't an option here;  I'll remove the check.

2020-09-16 00:44 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +)
See above

2020-09-16 00:46 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +LsstCamFilters0 = FilterDefinitionCollection(
I think it's clear, but sure, I'll change it.  `LsstCamFiltersBaseline`

2020-09-16 00:48 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +]
See above

2020-09-16 00:50 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +    *LsstCamFilters0,
TS3 used the LSSTCam filters before I worked on the code, and as I don't know what's out in the wild it seemed safer to leave them.

2020-09-16 00:50 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +    *LsstCamFilters0,
See comment on TS3

2020-09-16 00:54 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +            af = f"{abstract_filter}~{nd.replace('.', '_')}"
Comment added.

2020-09-16 01:12 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/lsstCamMapper.py
> +            except pexExceptions.NotFoundError:
I looked at the exception's type and didn't know that it was a subclass of `LookupError`.  Fixed.

2020-09-16 02:27 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/lsstCamMapper.py
> +            obsInfo = ObservationInfo(exp.getMetadata())
That wasted too much time...  Specifying `translator_class=self.translatorClass` broke the unit tests.  We weren't setting `LatissMapper.translator = LatissTranslator`.

2020-09-16 02:32 UTC, timj commented on python/lsst/obs/lsst/lsstCamMapper.py
> +            obsInfo = ObservationInfo(exp.getMetadata())
I'm very sorry about that. I don't know how I missed it from Latiss. I just checked imsim and ts8 and they do have it set.

2020-09-16 04:33 UTC, RobertLuptonTheGood commented on python/lsst/obs/lsst/filters.py
> +_latiss_gratings = ("ronchi90lpmm", "ronchi170lpmm", "EMPTY", "NONE", "UNKNOWN")
On second thoughts, I don't want to make this change as part of this ticket.  The reason is that the use of `NONE` is explicit in the comments in `to_physical_filter` (e.g. for unknown-filter biases).  I don't think that this is a good idea --- if we don't know the filter we don't know the filter, even if it's a bias or a dark --- but I think it's out of scope and should be its own ticket.

2020-09-16 12:40 UTC, merged