DM-32141: Get SFM working for LATISS
lsst/obs_lsst pull request #373
Opened 2021-11-23 14:15 UTC by mfisherlevine

2022-03-04 00:50 UTC, parejkoj requested changes

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +# allow configuration at a single point here, with logic following to allow
"with logic following"? What logic?

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +PHOTO_REFCAT_NAME = 'gaia_dr2_20200414'
The only reason I can think of to have these as named variables here is because we're still holding on to the vestigial `ref_dataset_name` from gen2. I'm not sure that's a good reason to start doing it this way right now.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +PHOTO_REFCAT_NAME = 'gaia_dr2_20200414'
Why not use ATLAS for photometry right now? I'd expect it to be better than gaia.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.filterMap = {}  # TODO: remove after DM-33270
No such TODO: that a won't fix.

However, you won't need any astrometry refcat config once DM-27013 merges; might be worth postponing this until then.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.retarget(LoadIndexedReferenceObjectsTask)
Irrelevant: only gen2.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.photoRefObjLoader.retarget(LoadIndexedReferenceObjectsTask)
irrelevant: gen2 only

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.photoCal.match.referenceSelection.magLimit.fluxField = "i_flux"
You want to always do refcat selection on `i` band, regardless of which filter you're using?

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +if 'gaia' in PHOTO_REFCAT_NAME:
I'd suggest not using gaia at all for photometry, and not including any logic for it here. It's just a bad match, and if we have a better gaia catalog in the future (e.g. a preprocessed DR3 that has some pseudo filters) it will look completely different.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +    # if no deblending has been done this is required to not crash
Why might this be in your list of plugins to cause this problem?

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.astrometry.wcsFitter.retarget(FitAffineWcsTask)
I do wish we'd switched to that by default... But that's not your problem.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.pixelMargin = 1000
You really want to pad by 1000 pixels? That's a lot. At least document why so many.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +MAXOFFSET = 3000
I think this and the pixelMargin below are distinct: this says "you're allowed to be this far off", which could be a good portion of the detector+margin.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +# apply a magnitude limit and decrease the SNR limit as we're only a 1.2m
All these comments are sentences, so should start with capital letters and have punctuation.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +# support independent refacts for astrometry and photometry
Capital letters and punctuation.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.astrometry.matcher.maxRotationDeg = 5.99
6 degrees only? Seems small if you're aiming for "we could be wildly off".

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/calibrate.py
> +# write old-style srcMatchFull
I don't think it's an "old style", it's just the full catalog with everything in it.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/characterizeImage.py
> +config.refObjLoader.retarget(LoadIndexedReferenceObjectsTask)
irrelevant: gen2 only

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/characterizeImage.py
> +config.refObjLoader.ref_dataset_name = REFCAT
This is gen2 only as well. I don't think you're configuring to use gaia at all in gen3 here.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/characterizeImage.py
> +config.doDeblend = False
other end of what?

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/characterizeImage.py
> +config.installSimplePsf.width = 81  # why is the default 11?!
"?!" - ??

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/characterizeImage.py
> +config.installSimplePsf.fwhm = 2.355*2
Where's this number from?

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/processCcd.py
> +# which just load the other file, which we should to stop doing in Gen3.
I don't understand this comment. The stuff under this seems unnecessary too.

I don't think you need `processCcd.py` at all, since all of the relevant classes have their own configs that get loaded appropriately, and there's no ProcessCcdTask in gen3, only the pipeline definition.

2022-03-04 00:50 UTC, parejkoj commented on config/latiss/transformSourceTable.py
> +config.functorFile = os.path.join('$OBS_LSST_DIR', 'policy', 'latiss', 'Source.yaml')
You don't need this file at all. As of [DM-28862](https://jira.lsstcorp.org/browse/DM-28862), there's a Source.yaml in pipe_tasks and the transform task uses it by default.

2022-03-04 00:50 UTC, parejkoj commented on policy/latiss/Source.yaml
> +funcs:
Don't need this file (DM-28862).

Unless you intentionally want something different from the default, in which case you need to document the header of this file.

2022-03-04 01:45 UTC, mfisherlevine commented on config/latiss/calibrate.py
> +PHOTO_REFCAT_NAME = 'gaia_dr2_20200414'
Wasn't available when the ticket was done, and still hasn't been tested and I don't think it's available everywhere yet. We will definitely update to it once it's been tested, but that'll be another ticket.

2022-03-04 01:46 UTC, mfisherlevine commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.filterMap = {}  # TODO: remove after DM-33270
Happy to drop a TODO to say fix it once it does, but this has been waiting for too long already and I don't want to block on something else, I've already suffered the drp_pipe rebase here 🙂

2022-03-04 01:47 UTC, mfisherlevine commented on config/latiss/calibrate.py
> +config.photoCal.match.referenceSelection.magLimit.fluxField = "i_flux"
I forget why I did that tbh. I will have to ask others to test what happens en masse if we change that, but it was there for a reason.

2022-03-04 01:48 UTC, mfisherlevine commented on config/latiss/calibrate.py
> +if 'gaia' in PHOTO_REFCAT_NAME:
I know it is, but it's much better than nothing if you're just trying to get the plumbing working, and again we didn't (and still don't quite) have ATLAS. Once that's there, and we confirm it covers the whole of the sky we care about I'll be happy to remove.

2022-03-04 01:48 UTC, mfisherlevine commented on config/latiss/calibrate.py
> +    # if no deblending has been done this is required to not crash
Don't know, that was just the default ones, and this is apparently necessary if you're turning deblending off. There might be a ticket to fix that? But I don't know what it is.

2022-03-04 01:49 UTC, mfisherlevine commented on config/latiss/calibrate.py
> +config.astrometry.matcher.maxRotationDeg = 5.99
Seems very small _indeed._ But it's the max allowed by the config, which is disasterous, but also life.

2022-03-04 01:50 UTC, mfisherlevine commented on config/latiss/characterizeImage.py
> +config.doDeblend = False
The regime in which one might worry about blending 🙂

2022-03-04 01:51 UTC, mfisherlevine commented on config/latiss/characterizeImage.py
> +config.installSimplePsf.width = 81  # why is the default 11?!
That's the number of pixels in the PSF model, as far as I can work out. 11 seems absurdly small and causes weird problems. I can't quite understand how this works for anyone.

2022-03-04 01:52 UTC, mfisherlevine commented on config/latiss/characterizeImage.py
> +config.installSimplePsf.fwhm = 2.355*2
I think/hope it's just doubling a 1" PSF. Anyway, it was just emperical twiddling, and the fact that the platescale is 2x  the LSST nominal.

2022-03-04 01:53 UTC, mfisherlevine commented on config/latiss/processCcd.py
> +# which just load the other file, which we should to stop doing in Gen3.
This ticket was originally for getting it working for Gen2 and Gen3, hence all the Gen2 stuff.

2022-03-04 01:53 UTC, mfisherlevine commented on config/latiss/transformSourceTable.py
> +config.functorFile = os.path.join('$OBS_LSST_DIR', 'policy', 'latiss', 'Source.yaml')
I think it's not the same. IIRC we had to make a bunch of changes to make it work here because we're not running everything.

2022-03-04 01:54 UTC, mfisherlevine commented on policy/latiss/Source.yaml
> +funcs:
As above.

2022-03-04 16:50 UTC, edennihy commented on config/latiss/calibrate.py
> +PHOTO_REFCAT_NAME = 'gaia_dr2_20200414'
I have confirmed the new ATLAS-REFCAT2 (https://jira.lsstcorp.org/browse/DM-33444) functionally for photometric calibration, but it still requires adding the ticket collection to the input collections (e.g. 'refcats/DM-33444') and I'm still verifying it vs Pan-STARRS calibration. I'm happy to put in the ticket and make this change once that work is done.

2022-03-05 00:41 UTC, parejkoj commented on policy/latiss/Source.yaml
> +funcs:
If you do need a separate file, please document why at the top (if you don't remember the details, at least diff it against the current version in pipe_tasks as a reminder).

2022-03-09 18:35 UTC, parejkoj commented on policy/latiss/Source.yaml
> +#    - base_LocalPhotoCalibErr
You need these to get calibrated fluxes in the output sourceTables.

2022-03-09 18:54 UTC, parejkoj commented on policy/latiss/Source.yaml
> +funcs:
Reiterating my comment above: If you really do need a separate file here, you need to document what has changed: Erik and I were just trying to figure out why the fluxes were incorrect.

Is there a way to do a "subtraction" from an existing yaml file, so that the difference with the standard version is explicit? Then as you get more things to work, you can just remove those lines from this file.

2022-04-11 22:32 UTC, edennihy commented on config/latiss/calibrate.py
> +PHOTO_REFCAT_NAME = 'gaia_dr2_20200414'
Confirmed ATLAS-REFCAT2 calibration, updated in 6f7b6a7

2022-04-11 23:10 UTC, edennihy commented on policy/latiss/Source.yaml
> +funcs:
File removed per ce10ce4, I confirmed we could use the default Source.yaml in pipe_tasks after turning on deblend in config.calibrate.py

2022-04-11 23:10 UTC, edennihy commented on config/latiss/transformSourceTable.py
> +config.functorFile = os.path.join('$OBS_LSST_DIR', 'policy', 'latiss', 'Source.yaml')
File removed per ce10ce4, I confirmed we could use the default Source.yaml in pipe_tasks after turning on deblend in config.calibrate.py

2022-04-11 23:10 UTC, edennihy commented on policy/latiss/Source.yaml
> +#    - base_LocalPhotoCalibErr
File removed per ce10ce4

2022-04-11 23:29 UTC, edennihy commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.filterMap = {}  # TODO: remove after DM-33270
updated TO-DO to reference DM-27013 instead

2022-05-09 18:02 UTC, parejkoj commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.pixelMargin = 1000
Document why such a large pixelMargin, please.

2022-05-09 18:36 UTC, edennihy commented on config/latiss/processCcd.py
> +# which just load the other file, which we should to stop doing in Gen3.
Removed in [50b7ad4]

2022-05-09 18:53 UTC, edennihy commented on config/latiss/calibrate.py
> +        atlasFilterMap[filt.band] = filt.band
There are additional filters that we exclude with this map are not matched in the ref catalog. E.g. without this map the task fails with 
`lsst.ctrl.mpexec.singleQuantumExecutor ERROR: Execution of task 'calibrate' on quantum {instrument: 'LATISS', detector: 0, visit: 2022050400240, ...} failed. Exception RuntimeError: Unknown reference filter lsst_u_smeared_flux
`

2022-05-09 21:04 UTC, timj commented on config/latiss/calibrate.py
> +        atlasFilterMap[filt.band] = filt.band
what is an "lsst_u_smeared_flux" filter? That's not an actual filter.

2022-05-09 21:37 UTC, parejkoj commented on config/latiss/calibrate.py
> +        atlasFilterMap[filt.band] = filt.band
If the goal is to not photometrically calibrate certain filters, I think that should be done when running the tasks, not abusing the filterMap in this way. I'm surprised that you don't get error when you've specified a filterMap like this (`r=r`, `g=g`, etc.): I'd expect to get a `RuntimeError: Could not find flux field(s) ...` with a filterMap that only contains those things.

The error you're quoting above should only happen if you have `lsst_u_smeared` in the filterMap.

Is the goal to run some kind of minimal photometric calibration on the "non-standard" filters, or to not run any on them?

2022-05-11 16:29 UTC, edennihy commented on config/latiss/characterizeImage.py
> +config.doDeblend = False
This is actually the default setting for characterizeImage so I will remove.

2022-05-11 17:37 UTC, edennihy commented on config/latiss/calibrate.py
> +config.astromRefObjLoader.retarget(LoadIndexedReferenceObjectsTask)
Retarget removed.

2022-05-11 17:38 UTC, edennihy commented on config/latiss/characterizeImage.py
> +config.refObjLoader.ref_dataset_name = REFCAT
This is still needed to satisfy the Gen2/Gen3 consistency check.

2022-05-11 18:06 UTC, edennihy commented on config/latiss/characterizeImage.py
> +config.refObjLoader.ref_dataset_name = REFCAT
We have been happily operating with just Gaia here (which is the default), so I don't think this is needed anymore. I will remove this block.

2022-05-11 19:08 UTC, edennihy commented on config/latiss/calibrate.py
> +PHOTO_REFCAT_NAME = 'gaia_dr2_20200414'
We have to keep the `ref_dataset_name` in until consistency check is removed, so I'll leave this in for now.

2022-05-12 17:00 UTC, closed without merging

2022-05-12 17:02 UTC, parejkoj commented
@timj : why did you close this PR without merging it?