Tickets/dm 39999
lsst/obs_lsst pull request #462
Opened 2023-07-12 22:55 UTC by Snyder005

Add UC Davis Beam Simulator ITL Camera to obs_lsst.

2023-12-06 22:19 UTC, timj requested changes
The Jira ticket does not make it clear but this PR is going to result in the older data not being importable into gen3 butlers. Is everyone okay with that? Today the "SAO" test stand data can be ingested but next week it won't be. As an archivist this seems wrong to me but if people are deleting all that data then that's going to be okay.

We can't merge this PR without some test headers being added to ensure that these files can be translated properly.

2023-12-06 22:19 UTC, timj commented on python/lsst/obs/lsst/translators/lsst_ucdcam.py
> -
This line needs to go back I think.

2023-12-06 22:19 UTC, timj commented on tests/test_translator.py
> -    def test_ucdcam_translator(self):
There needs to be a check of the translator. Please add a couple of test headers back (with different chips) and ensure that you are getting the expected values out.

2023-12-14 19:36 UTC, Snyder005 commented on tests/test_translator.py
> -    def test_ucdcam_translator(self):
I added some test headers for the E2V and ITL CCDs. As I understand it I know need a translator test object where I define the `test_data` dictionary which then is compared to the header information I put in the test header YAML files?

2023-12-14 23:20 UTC, timj commented on tests/test_translator.py
> -    def test_ucdcam_translator(self):
The code deleted from this file should show you what form the replacement code needs to be. You can get the expected output by running `astrometadata -p lsst.obs.lsst.translators translate` on the test yaml file.

I take it there is agreement that none of the 2018 code should ever be read into butler again?

2024-01-10 04:05 UTC, Snyder005 commented on tests/test_translator.py
> -    def test_ucdcam_translator(self):
I believe the translator has been written completely now.  I was able to run scons without any failures.

2024-01-10 21:10 UTC, Snyder005 commented
Added test headers and wrote the test translator function for the new LSST-UCDCam camera definition.

2024-01-10 21:17 UTC, timj commented
Can you confirm that the old data that this code worked with before will never needed to be looked at again? I'm yet to get a formal statement that those data are now irrelevant and nothing will need to look at them.

2024-01-10 22:15 UTC, Snyder005 commented
Yes, the old data was only used by a few of us here at Davis and was never made available at USDF. We don't intend to use it within the DM Butler framework again.

2024-01-16 16:49 UTC, timj approved these changes
Thanks for the changes. I've made some minor comments but I would like the class moved back where it was if possible to show that the changes are small.

2024-01-16 16:49 UTC, timj commented on python/lsst/obs/lsst/_instrument.py
> +class LsstUCDCam(LsstCam):
Can you please move this class back to where it was (above LsstTS3) so it is more obvious what has changed and what has stayed the same? I think the only thing that has changed is the filter definition (other than you changing the order of the properties).

2024-01-16 16:49 UTC, timj commented on python/lsst/obs/lsst/translators/lsst_ucdcam.py
> +            instrume = header["INSTRUME"].lower()
```suggestion
            if header["INSTRUME"].lower() in (cls.supported_instrument.lower(), "LSST-UCDCam-ITL".lower()):
```
?

2024-01-16 16:49 UTC, timj commented on python/lsst/obs/lsst/translators/lsst_ucdcam.py
> +            elif instrume == "LSST-UCDCam-ITL".lower():
If ever we learn that this is a hotspot we could replace the string with  `"lsst-ucdcam-itl"`...

2024-01-16 16:49 UTC, timj commented on tests/test_gen3.py
> -                                         "ucd/raw/2018-12-05/20181205233148-S00-det000.fits")
You haven't got a stripped FITS file you want to test you can ingest into a butler?

2024-01-16 19:13 UTC, Snyder005 commented on tests/test_gen3.py
> -                                         "ucd/raw/2018-12-05/20181205233148-S00-det000.fits")
By "stripped FITS" file, how exactly is this modified form a regular image file.  It sounds like some data is removed, to decrease the file size.

2024-01-16 19:20 UTC, timj commented on tests/test_gen3.py
> -                                         "ucd/raw/2018-12-05/20181205233148-S00-det000.fits")
Yes. See eg https://pipelines.lsst.io/v/weekly/modules/lsst.obs.lsst/testing.html#butler-tests for example script to do that.

2024-01-18 06:10 UTC, merged