Add SDSS_65mm filter options to grating slot for LATISS.
lsst/obs_lsst pull request #473
Opened 2023-10-05 22:01 UTC by edennihy

2023-10-05 22:39 UTC, ktlim commented
Might be nice to filter out combinations that will never be used; right now the nested loops will make every combination.

2023-10-05 22:41 UTC, ktlim commented
Also, you have aliases for the filter in the filter wheel (new line 357); do you need aliases for the filter in the grating wheel?

2023-10-05 22:56 UTC, edennihy commented
Do you have a suggestion for a quick way to filter out all of the (anticipated) unused combinations?

2023-10-05 22:56 UTC, edennihy commented
To your second point, I noticed the SDSS65mm filter definitions above did not have alias definitions, so I wasn't sure if that was needed. Same thing for the afw_name, unless those are being defined elsewhere.

2023-10-05 23:21 UTC, edennihy commented
Okay, I added some simple logic to only allow the (empty~SDSS_65mm) combination and a check on the grating alias if needed.

2023-10-06 01:24 UTC, timj commented
How many combinations do you end up with after this change?

```
$ butler create tmp
$ butler register-instrument tmp lsst.obs.lsst.Latiss
$ butler query-dimension-records tmp physical_filter
```
?

2023-10-06 14:36 UTC, edennihy commented
The total number of filters prior to change is 701, total number after is 707. The majority are due to combinations with the pinhole masks. We could filter some of those as well if we want (for example, order blocking filters will not be used with the pinhole masks).

2023-10-10 16:41 UTC, timj requested changes
I think this needs a bit of tidying up.

It's great that you managed to filter out all the combinations. I agree that another pass in the future to remove impossible combinations would be great.

2023-10-10 16:41 UTC, timj commented on python/lsst/obs/lsst/filters.py
> +                    FilterDefinition(physical_filter="SDSSu_65mm",
Can you add a comment above this block explaining why these filters are nominally in the gratings list?

2023-10-10 16:41 UTC, timj commented on python/lsst/obs/lsst/filters.py
> +                    FilterDefinition(physical_filter="SDSSg_65mm",
I worry a bit that this duplication of class constructors with the filter list is going to leave us susceptible to typos in the future. Maybe we define a `sdss_filters` list and then use `*sdss_filters` in here and the filter list above? That would guarantee that we really are duplicating.

2023-10-10 16:41 UTC, timj commented on python/lsst/obs/lsst/filters.py
> +        if hasattr(grating, "physical_filter"):
I think you can do something like:

```python
grating_name = getattr(grating, "physical_filter", grating)
new_name = FILTER_DELIMITER.join([filter.physical_filter, grating_name])
```

2023-10-10 16:41 UTC, timj commented on python/lsst/obs/lsst/filters.py
> +        # For gratings set the band to the band of the filter. If an SDSS_65mm
This commit is far more specific than the code that is written here. The comment should be talking about what happens if the grating is a filter definition. SDSS_65mm is never checked.

2023-10-10 16:41 UTC, timj commented on python/lsst/obs/lsst/filters.py
> +            combo = FilterDefinition(physical_filter=new_name,
Since the above code is mainly working out the parameters for these calls, maybe use one `isinstance` instead to calculate the parameters instead of doing lots of hasattr tests?

2023-10-10 18:47 UTC, timj approved these changes

2023-10-10 19:55 UTC, merged