DM-43436: Enable OBJECT and AZEL translations for LSSTCam
lsst/obs_lsst pull request #517
Opened 2024-03-23 01:41 UTC by timj

ComCamSim needs special code because the AZEL values are missing and airmass is inconsistent with the observation date.

2024-03-23 16:00 UTC, timj commented
It has been suggested on Slack that I also add header fixup code for comcamsim to copy RA/DEC into [RA|DEC][START|END} since they must be identical in simulated data like this.

This doesn't solve the AZEL problem but does mean that downstream of ISR the header will be filled in.

2024-03-25 00:09 UTC, jchiang87 requested changes
Looks good, though I think the controller code test for simulated data should include "S".

2024-03-25 00:09 UTC, jchiang87 commented on python/lsst/obs/lsst/translators/lsst.py
>              if controller in "HPQ":
Should this test also include controller "S"?

2024-03-25 20:17 UTC, timj commented on python/lsst/obs/lsst/translators/lsst.py
>              if controller in "HPQ":
@jchiang87  I fixed this but I also added some header fixups for things like RASTART/RAEND and fixed an age-old ComCam translator bug from #167. It's quite a lot of code so I've asked for a re-review.

2024-03-25 20:17 UTC, timj commented
I will fix the problem with the day_obs offset calculation on another ticket. It's not important for ops rehearsal since we are not yet using butler universion 6 for that.

2024-03-25 20:45 UTC, jchiang87 approved these changes
lgtm.

2024-03-26 04:55 UTC, merged